CI:     1) Fixed the problem that master schdules triggered target_ut_test by mistake.     2) Merge build_ut into build stage.     3) Push operation does not execute the assign_test stage.     4) Add pre_check stage. Pipeline does not succeed unless example_test/unit_test tags are added in MR.     5) Add docs_test pipeline.     6) Add rtmp and av_muxer_sdcard to apps.json.     7) Fix the issue that checking apps.json failed.     8) Add ut_auto_config.sh     9) Delete esp-idf v3.3 related test.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,6 @@
 stages:
+  - pre_check
   - build
-  - build_ut
   - assign_test
   - target_test
 #  - example_test
@@ -21,24 +21,25 @@ variables:
   IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
   CI_TARGET_UT_TEST_CONFIG_FILE: "$CI_PROJECT_DIR/.gitlab/ci/target-ut-test.yml"
   IDF_SKIP_CHECK_SUBMODULES: 1
+  GIT_DEPTH: 1
 
 .set_idf_version_and_update: &set_idf_version_and_update
   $ADF_PATH/tools/ci/set_idf.sh ${IDF_VERSION}
 
 .execute_submodules: &execute_submodules
   if [[ "$DEEP_CLONE" == "true" ]]; then
-  git submodule update --init;
+    git submodule update --init;
   else
-  git -c submodule."esp-idf".update=none submodule update --init;
-  git submodule | grep esp-idf;
-  export ORIG_HEAD=`git submodule | grep "esp-idf" | sed -r 's/-(.*) esp-idf/\1/g'`;
-  echo ${ORIG_HEAD};
-  rm esp-idf -rf;mkdir esp-idf;
-  cd esp-idf;git init;
-  git remote add origin ${GITLAB_SSH_SERVER}/idf/esp-idf.git;
-  git fetch origin ${ORIG_HEAD}:${ORIG_HEAD} --depth 1;
-  git checkout ${ORIG_HEAD};
-  cd -;
+    git -c submodule."esp-idf".update=none submodule update --init;
+    git submodule | grep esp-idf;
+    export ORIG_HEAD=`git submodule | grep "esp-idf" | sed -r 's/-(.*) esp-idf/\1/g'`;
+    echo ${ORIG_HEAD};
+    rm esp-idf -rf; mkdir esp-idf;
+    cd esp-idf; git init;
+    git remote add origin ${GITLAB_SSH_SERVER}/idf/esp-idf.git;
+    git fetch origin ${ORIG_HEAD}:${ORIG_HEAD} --depth 1;
+    git checkout ${ORIG_HEAD};
+    cd -;
   fi
 
 before_script:
@@ -57,6 +58,7 @@ before_script:
   # - sed -i "s%https://github.com/espressif/esp-sr.git%${GITLAB_SSH_SERVER}/speech-recognition-internal/esp_sr_public.git%" .gitmodules
   - git config --global http.postBuffer 524288000
   - *execute_submodules
+  - pip install --upgrade cmake
   - echo "current path:"$(pwd)
   - cd $ADF_PATH/..
   - if [[ ! -d "$ADF_PATH/../adf-libs-ut/" ]]; then git clone ssh://git@gitlab.espressif.cn:27227/adf/adf-libs-ut.git;else echo "adf-libs-ut folder already exists";fi
@@ -68,9 +70,6 @@ before_script:
   - source $ADF_PATH/tools/ut/switch_branch.sh
   - set -e -o pipefail
 
-  # - cd $IDF_PATH
-  # - git checkout $IDF_VERSION
-  # - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)"
   - source $IDF_PATH/tools/ci/setup_python.sh
   - if [ "$IDF_VERSION" != "release/v4.4" ];then source esp-idf/tools/ci/configure_ci_environment.sh;fi
 
@@ -126,41 +125,6 @@ before_script:
     - make
     - make print_flash_cmd > build/download.config
 
-build_docs:
-  stage: build
-  image: $CI_DOCKER_REGISTRY/esp-idf-doc-env:v7
-  tags:
-    - build_docs
-  artifacts:
-    when: always
-    paths:
-      # English version of documentation
-      - docs/en/doxygen-warning-log.txt
-      - docs/en/sphinx-warning-log.txt
-      - docs/en/sphinx-warning-log-sanitized.txt
-      - docs/en/_build/html
-      # Chinese version of documentation
-      - docs/zh_CN/doxygen-warning-log.txt
-      - docs/zh_CN/sphinx-warning-log.txt
-      - docs/zh_CN/sphinx-warning-log-sanitized.txt
-      - docs/zh_CN/_build/html
-    expire_in: 1 mos
-  script:
-    - source /opt/pyenv/activate && pyenv global 3.6.10
-    - pip install "setuptools<57.5.0"
-    - pip install "funcparserlib==0.3.6"
-    - /opt/pyenv/pyenv-1.2.16/versions/3.6.10/bin/python -m pip install --user -r docs/requirements.txt
-    - cd docs
-    - ./check_lang_folder_sync.sh
-    - cd en
-    - make gh-linkcheck
-    - make html
-    - ../check_doc_warnings.sh
-    - cd ../zh_CN
-    - make gh-linkcheck
-    - make html
-    - ../check_doc_warnings.sh
-
 .assign_test:
   tags:
     - assign_test
@@ -190,11 +154,26 @@ build_docs:
     # assign example tests
     - python $TEST_FW_PATH/CIAssignExampleTest.py $CI_PROJECT_DIR/examples $CI_PROJECT_DIR/.gitlab-ci.yml $EXAMPLE_CONFIG_OUTPUT_PATH
 
+check_labels:
+  image: $CI_DOCKER_REGISTRY/esp32-ci-env$BOT_DOCKER_IMAGE_TAG
+  stage: pre_check
+  rules:
+    - if: '($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_BRANCH =~ /^release\/v/ || $CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?($|-)/) && $CI_PIPELINE_SOURCE != "schedule"'
+      when: never
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && ($CI_PIPELINE_SOURCE == "push")'
+      when: never
+    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != "master"'
+  before_script:
+    - echo "skip default before_script"
+  script:
+    - if [[ "$CI_MERGE_REQUEST_LABELS" =~ "unit_test" ]]; then echo "unit_test label exists"; else echo "warning:unit_test label is missing.Please add the unit_test and example_test label to the MR for the pipeline to succeed"; exit 1; fi
+    - if [[ "$CI_MERGE_REQUEST_LABELS" =~ "example_test" ]]; then echo "example_test label exists"; else echo "waring:example_test label is missing.Please add the example_test and unit_test label to the MR for the pipeline to succeed"; exit 1; fi
+
 push_to_github:
   stage: deploy
-  only:
-    - master
-    - /^release\/v/
+  rules:
+    - if: '($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_BRANCH =~ /^release\/v/ || $CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?($|-)/) && $CI_PIPELINE_SOURCE != "schedule"'
 #  when: on_success
   image: $CI_DOCKER_REGISTRY/esp32-ci-env
   variables:
@@ -208,6 +187,7 @@ push_to_github:
     - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
+    - git fetch --unshallow
     - git remote remove github &>/dev/null || true
     - git remote add github git@github.com:espressif/esp-adf.git
     - tools/ci/push_to_github.sh
@@ -218,3 +198,4 @@ include:
   - '.gitlab/ci/assign-test.yml'
   - '.gitlab/ci/target-ut-test.yml'
   - '.gitlab/ci/rules.yml'
+  - '.gitlab/ci/docs.yml'
